---
name: stale repo identifier
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '3 2 1 * *'
permissions:
  contents: read
jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Run stale_repos tool
        uses: docker://ghcr.io/github/stale_repos:v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORGANIZATION: github
          INACTIVE_DAYS: 1
      - name: Create issue
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94
        with:
          title: Stale repository report
          content-filepath: ./stale_repos.md
          assignees: zkoppert
